# Root serverless.yml for local development and unified API
service: namecard-local
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  stage: ${opt:stage, 'local'}
  environment:
    NODE_ENV: ${opt:stage, 'local'}
    STAGE: ${opt:stage, 'local'}
    DATABASE_URL: ${env:DATABASE_URL, 'postgresql://namecard_user:namecard_password@localhost:5432/namecard_dev'}
    JWT_SECRET: ${env:JWT_SECRET, 'your-super-secret-jwt-key-for-local-development-only'}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN, '7d'}
    JWT_REFRESH_EXPIRES_IN: ${env:JWT_REFRESH_EXPIRES_IN, '30d'}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID, 'dummy-pool-id'}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, 'dummy-client-id'}
    COGNITO_REGION: ${env:COGNITO_REGION, 'ap-southeast-1'}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID, 'dummy'}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY, 'dummy'}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME, 'dummy-bucket'}
    CLOUDFRONT_DOMAIN: ${env:CLOUDFRONT_DOMAIN, 'dummy-domain.cloudfront.net'}
    PERPLEXITY_API_KEY: ${env:PERPLEXITY_API_KEY, 'dummy-perplexity-key'}

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
    packager: 'npm'

  serverless-offline:
    httpPort: 3001
    host: 0.0.0.0
    prefix: api/v1
    corsAllowHeaders: 'accept,content-type,x-api-key,authorization'
    corsAllowOrigin: '*'
    corsAllowMethods: 'GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS'

functions:
  # Auth service proxy
  auth-proxy:
    handler: local/auth-proxy.handler
    events:
      - http:
          path: auth/{proxy+}
          method: ANY
          cors: true

  # Cards service proxy  
  cards-proxy:
    handler: local/cards-proxy.handler
    events:
      - http:
          path: cards/{proxy+}
          method: ANY
          cors: true

  # Upload service proxy
  upload-proxy:
    handler: local/upload-proxy.handler
    events:
      - http:
          path: upload/{proxy+}
          method: ANY
          cors: true

  # OCR/Scan service proxy
  scan-proxy:
    handler: local/scan-proxy.handler
    events:
      - http:
          path: scan/{proxy+}
          method: ANY
          cors: true

  # Enrichment service proxy
  enrichment-proxy:
    handler: local/enrichment-proxy.handler
    events:
      - http:
          path: enrichment/{proxy+}
          method: ANY
          cors: true

  # Health check
  health:
    handler: local/health.handler
    events:
      - http:
          path: health
          method: GET
          cors: true