# Local development environment configuration
DATABASE_URL: "postgresql://namecard_user:namecard_password@localhost:5432/namecard_dev"

# JWT Configuration
JWT_SECRET: "local-development-secret-key-change-in-production"
JWT_EXPIRES_IN: "24h"

# Cognito Configuration (using existing staging values for local)
COGNITO_USER_POOL_ID: "ap-southeast-1_bOA22s0Op"
COGNITO_CLIENT_ID: "5s54d0ifpt3frtvut325uglrjp"
COGNITO_REGION: "ap-southeast-1"

# S3 Configuration (using existing staging values for local)
S3_BUCKET_NAME: "namecard-images-staging-145006476362"
S3_REGION: "ap-southeast-1"
S3_CDN_DOMAIN: "d1357e576dd65p.cloudfront.net"

# Upload Configuration
MAX_FILE_SIZE: "10485760" # 10MB
ALLOWED_FILE_TYPES: "image/jpeg,image/png,image/heic,image/webp"

# OCR Configuration
OCR_CONFIDENCE_THRESHOLD: "80"

# Perplexity AI Configuration (use dummy values for local)
PERPLEXITY_API_KEY: "pplx-dummy-key-for-local-development"
PERPLEXITY_BASE_URL: "https://api.perplexity.ai"
PERPLEXITY_RATE_LIMIT_RPM: "60"
PERPLEXITY_RATE_LIMIT_RPD: "1000"
PERPLEXITY_TIMEOUT: "30000"
PERPLEXITY_MAX_RETRIES: "2"
PERPLEXITY_BACKOFF_MS: "3000"

# Enrichment Configuration
ENRICHMENT_ENABLED_SOURCES: "perplexity"
PERPLEXITY_ENABLED: "true"
PERPLEXITY_WEIGHT: "0.9"
PERPLEXITY_TRUST_LEVEL: "88"

# Redis Configuration (for local development)
REDIS_URL: "redis://localhost:6379"
REDIS_PASSWORD: ""

# CORS Configuration
CORS_ORIGIN: "http://localhost:3000,http://localhost:5173,http://localhost:8080"

# Logging
LOG_LEVEL: "debug"