#!/usr/bin/env bash
set -euo pipefail

STACK_NAME=${STACK_NAME:-NameCardInfra-staging}
AWS_REGION=${AWS_REGION:-ap-southeast-1}
AWS_PROFILE=${AWS_PROFILE:-namecard-staging}
OUTPUT_FILE=${OUTPUT_FILE:-.env.hosted-staging}

read_stack_output() {
  local key=$1
  aws --profile "$AWS_PROFILE" --region "$AWS_REGION" \
    cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey==\`$key\`].OutputValue" \
    --output text
}

S3_BUCKET_NAME=$(read_stack_output S3BucketNameEnvVar)
S3_REGION=$(read_stack_output S3RegionEnvVar)
S3_CDN_DOMAIN=$(read_stack_output S3CdnDomainEnvVar)

if [[ -z "$S3_BUCKET_NAME" || -z "$S3_REGION" ]]; then
  echo "Failed to resolve stack outputs from $STACK_NAME in $AWS_REGION" >&2
  exit 1
fi

cat <<EOV > "$OUTPUT_FILE"
# Generated by scripts/fetch-hosted-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
S3_BUCKET_NAME=$S3_BUCKET_NAME
S3_REGION=$S3_REGION
S3_CDN_DOMAIN=$S3_CDN_DOMAIN
TEXTRACT_REGION=${TEXTRACT_REGION:-$S3_REGION}
EOV

echo "Wrote hosted environment values to $OUTPUT_FILE"
