name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build packages
        run: npm run build

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy infrastructure
        run: |
          cd infrastructure
          npm ci
          npx cdk deploy --context environment=production --require-approval never

      - name: Deploy frontend
        run: |
          cd packages/web
          npm run build
          # Deploy to S3/CloudFront for production
          echo "Deploying frontend to production environment"

      - name: Deploy API
        run: |
          cd packages/api
          npm run build
          # Deploy to ECS for production
          echo "Deploying API to production environment"

      - name: Deploy workers
        run: |
          cd packages/workers
          npm run build
          npm run deploy:prod
